[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.embed_txtfiles =
    certs/root_current.pem

build_flags =
    -D LOG_LOCAL_LEVEL=ESP_LOG_INFO
    -D AUTHSPHERE-ALLOW-HTTP-DEV
