from typing import Protocol

class BrokerAdmin(Protocol):
    async def upsert_role(self, role_name: str, pub_topics: list[str], sub_topics: list[str]) -> None: ...
    async def upsert_client(self, entity_id: str, role_name: str) -> None: ...
    async def set_client_enabled(self, entity_id: str, enabled: bool) -> None: ...
    async def delete_client(self, entity_id: str) -> None: ...
    async def kick(self, entity_id: str) -> None: ...
